INSERT INTO users (id, name, email, password_hash, role, avatar, status, last_login, created_at)
VALUES
  ('user-admin-001', 'Admin User', 'admin@greensky.com', '', 'admin', 'AU', 'active', NOW(), NOW()),
  ('user-tech-001', 'Lead Technician', 'lead.tech@greensky.com', '', 'technician', 'LT', 'active', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO technicians (
  id, user_id, name, email, phone, avatar, specialization, rating, projects_completed, active_projects, status, join_date
)
VALUES
  ('tech-001', 'user-tech-001', 'Lead Technician', 'lead.tech@greensky.com', '+63 900 000 0001', 'LT', 'Rooftop Installation', 4.8, 12, 1, 'busy', CURRENT_DATE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO projects (
  id, name, client, location, status, priority, start_date, end_date, budget, progress, description, project_lead
)
VALUES
  (
    'proj-001',
    'Starter Solar Installation',
    'Starter Client',
    'Metro Manila',
    'ongoing',
    'high',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '45 day',
    150000,
    20,
    'Initial seeded project after DB migration.',
    'tech-001'
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO project_technicians (project_id, technician_id)
VALUES ('proj-001', 'tech-001')
ON CONFLICT (project_id, technician_id) DO NOTHING;

INSERT INTO tasks (
  id, project_id, title, description, status, priority, assigned_to, due_date, created_at
)
VALUES
  (
    'task-001',
    'proj-001',
    'Initial site inspection',
    'Seed task generated by db/seed.sql',
    'in_progress',
    'high',
    'tech-001',
    CURRENT_DATE + INTERVAL '7 day',
    CURRENT_DATE
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO bookings (
  id, reference_no, service_type, date, time, status, technician, address, notes, amount
)
VALUES
  (
    'bk-001',
    'GS-DB-0001',
    'solar_panel_installation',
    CURRENT_DATE + INTERVAL '3 day',
    '09:00 AM',
    'pending',
    'Lead Technician',
    'Metro Manila',
    'Seed booking from DB.',
    150000
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO documents (
  id, title, type, file_size, uploaded_at, project_name, status, approval_status
)
VALUES
  (
    'doc-001',
    'Seed Installation Contract',
    'contract',
    '120 KB',
    CURRENT_DATE,
    'Starter Solar Installation',
    'active',
    'approved'
  )
ON CONFLICT (id) DO NOTHING;
